# example configuration file.

# name title
title = "TEST TOML"
# data, for processing
[database]
numbers = ["testNumber.conf","test2Number.conf","test3Number.conf"]
pause   = 3
# Arithmetic operators for basic arithmetic operations
[operators]
action = "+"